[package]
name = "app"
version = "0.1.0"
edition = "2024"
description = "Wasix app"
repository = "https://github.com/jurevans/wasi-demo"
license = "MIT"

[dependencies]
lib = { path = "../lib", default-features = false, features = [] }
